# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f18b0160240d33205ddb96ff0cdd15216027dc9eddb6d919ffcdb3535a9fa64789977009d0c267ac837c1a767073adba54bd88b7edf0f68cec54ac1c2441c7f

test:
  secret_key_base: 2358b8a9d7e5a6b232ba8dce8b87b9e31fd00652c23f9e43d996c1190b564e87632af1dfe6d40bec37b6759becc1502fff99534db71a53a6bba6ddaa463d55c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
